name: Dispatch website workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github
      - .gitignore
      - README.md
      - giscus*

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Call GitHub REST API
        env:
          TOKEN: ${{ secrets.WEBSITE_GH_ACTIONS_TOKEN }}
          REPO: rea1shane/website
          REF: main
          WORKFLOW_ID: update-posts.yaml
        run: |
          curl \
            -fL \
            --retry 3 \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ env.TOKEN }}" \
            https://api.github.com/repos/${{ env.REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches \
            -d '{"ref":"${{ env.REF }}"}'
